[build]
  command = "remix build"
  publish = "public"

[functions]
  included_files = ["app/assets/**"]

[dev]
  command = "remix watch"
  port = 3001
  autoLaunch = false
  framework = "remix"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/server"
  status = 200

[[headers]]
  for = "/build/*"
  [headers.values]
    "Cache-Control" = "public, max-age=31536000, s-maxage=31536000"
